// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.14.0
// source: home/corp.proto

package home

import (
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostCorpTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Age  int32  `protobuf:"varint,2,opt,name=age,proto3" json:"age,omitempty"`
}

func (x *PostCorpTicketRequest) Reset() {
	*x = PostCorpTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_home_corp_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostCorpTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCorpTicketRequest) ProtoMessage() {}

func (x *PostCorpTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_home_corp_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCorpTicketRequest.ProtoReflect.Descriptor instead.
func (*PostCorpTicketRequest) Descriptor() ([]byte, []int) {
	return file_home_corp_proto_rawDescGZIP(), []int{0}
}

func (x *PostCorpTicketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *PostCorpTicketRequest) GetAge() int32 {
	if x != nil {
		return x.Age
	}
	return 0
}

type PostCorpTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Code    int32          `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message string         `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	Data    *emptypb.Empty `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
}

func (x *PostCorpTicketResponse) Reset() {
	*x = PostCorpTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_home_corp_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PostCorpTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PostCorpTicketResponse) ProtoMessage() {}

func (x *PostCorpTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_home_corp_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PostCorpTicketResponse.ProtoReflect.Descriptor instead.
func (*PostCorpTicketResponse) Descriptor() ([]byte, []int) {
	return file_home_corp_proto_rawDescGZIP(), []int{1}
}

func (x *PostCorpTicketResponse) GetCode() int32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *PostCorpTicketResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *PostCorpTicketResponse) GetData() *emptypb.Empty {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetCorpTicketRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Url  string `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *GetCorpTicketRequest) Reset() {
	*x = GetCorpTicketRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_home_corp_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCorpTicketRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCorpTicketRequest) ProtoMessage() {}

func (x *GetCorpTicketRequest) ProtoReflect() protoreflect.Message {
	mi := &file_home_corp_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCorpTicketRequest.ProtoReflect.Descriptor instead.
func (*GetCorpTicketRequest) Descriptor() ([]byte, []int) {
	return file_home_corp_proto_rawDescGZIP(), []int{2}
}

func (x *GetCorpTicketRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *GetCorpTicketRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetCorpTicketResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Timestamp int32  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	Noncestr  string `protobuf:"bytes,2,opt,name=noncestr,proto3" json:"noncestr,omitempty"`
	CorpId    string `protobuf:"bytes,3,opt,name=corpId,proto3" json:"corpId,omitempty"`
	Sign      string `protobuf:"bytes,4,opt,name=sign,proto3" json:"sign,omitempty"`
	Agentid   int32  `protobuf:"varint,5,opt,name=agentid,proto3" json:"agentid,omitempty"`
}

func (x *GetCorpTicketResponse) Reset() {
	*x = GetCorpTicketResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_home_corp_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *GetCorpTicketResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCorpTicketResponse) ProtoMessage() {}

func (x *GetCorpTicketResponse) ProtoReflect() protoreflect.Message {
	mi := &file_home_corp_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCorpTicketResponse.ProtoReflect.Descriptor instead.
func (*GetCorpTicketResponse) Descriptor() ([]byte, []int) {
	return file_home_corp_proto_rawDescGZIP(), []int{3}
}

func (x *GetCorpTicketResponse) GetTimestamp() int32 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *GetCorpTicketResponse) GetNoncestr() string {
	if x != nil {
		return x.Noncestr
	}
	return ""
}

func (x *GetCorpTicketResponse) GetCorpId() string {
	if x != nil {
		return x.CorpId
	}
	return ""
}

func (x *GetCorpTicketResponse) GetSign() string {
	if x != nil {
		return x.Sign
	}
	return ""
}

func (x *GetCorpTicketResponse) GetAgentid() int32 {
	if x != nil {
		return x.Agentid
	}
	return 0
}

var File_home_corp_proto protoreflect.FileDescriptor

var file_home_corp_proto_rawDesc = []byte{
	0x0a, 0x0f, 0x68, 0x6f, 0x6d, 0x65, 0x2f, 0x63, 0x6f, 0x72, 0x70, 0x2e, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x12, 0x07, 0x78, 0x64, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x1a, 0x1c, 0x67, 0x6f, 0x6f, 0x67,
	0x6c, 0x65, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x6e, 0x6e, 0x6f, 0x74, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x73, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x1a, 0x1b, 0x67, 0x6f, 0x6f, 0x67, 0x6c, 0x65,
	0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x65, 0x6d, 0x70, 0x74, 0x79, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x3d, 0x0a, 0x15, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x72,
	0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x12,
	0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x10, 0x0a, 0x03, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52,
	0x03, 0x61, 0x67, 0x65, 0x22, 0x72, 0x0a, 0x16, 0x50, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x72, 0x70,
	0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x12,
	0x0a, 0x04, 0x63, 0x6f, 0x64, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x63, 0x6f,
	0x64, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2a, 0x0a, 0x04,
	0x64, 0x61, 0x74, 0x61, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x67, 0x6f, 0x6f,
	0x67, 0x6c, 0x65, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x45, 0x6d, 0x70,
	0x74, 0x79, 0x52, 0x04, 0x64, 0x61, 0x74, 0x61, 0x22, 0x3c, 0x0a, 0x14, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x72, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x12, 0x10, 0x0a, 0x03, 0x75, 0x72, 0x6c, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75,
	0x72, 0x6c, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x97, 0x01, 0x0a, 0x15, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x72, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x1c, 0x0a, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x05, 0x52, 0x09, 0x74, 0x69, 0x6d, 0x65, 0x73, 0x74, 0x61, 0x6d, 0x70, 0x12, 0x1a,
	0x0a, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x6e, 0x6f, 0x6e, 0x63, 0x65, 0x73, 0x74, 0x72, 0x12, 0x16, 0x0a, 0x06, 0x63, 0x6f,
	0x72, 0x70, 0x49, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x63, 0x6f, 0x72, 0x70,
	0x49, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x04, 0x73, 0x69, 0x67, 0x6e, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x69,
	0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x69, 0x64,
	0x32, 0xf2, 0x01, 0x0a, 0x0b, 0x43, 0x72, 0x6f, 0x70, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65,
	0x12, 0x6d, 0x0a, 0x0d, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x72, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x1d, 0x2e, 0x78, 0x64, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43,
	0x6f, 0x72, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74,
	0x1a, 0x1e, 0x2e, 0x78, 0x64, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x47, 0x65, 0x74, 0x43, 0x6f,
	0x72, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x22, 0x1d, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x17, 0x12, 0x15, 0x2f, 0x61, 0x70, 0x69, 0x2f, 0x76,
	0x31, 0x2f, 0x67, 0x65, 0x74, 0x43, 0x6f, 0x72, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x12,
	0x74, 0x0a, 0x0e, 0x70, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x72, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65,
	0x74, 0x12, 0x1e, 0x2e, 0x78, 0x64, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x43, 0x6f, 0x72, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x1f, 0x2e, 0x78, 0x64, 0x2e, 0x68, 0x6f, 0x6d, 0x65, 0x2e, 0x50, 0x6f, 0x73, 0x74,
	0x43, 0x6f, 0x72, 0x70, 0x54, 0x69, 0x63, 0x6b, 0x65, 0x74, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e,
	0x73, 0x65, 0x22, 0x21, 0x82, 0xd3, 0xe4, 0x93, 0x02, 0x1b, 0x22, 0x16, 0x2f, 0x61, 0x70, 0x69,
	0x2f, 0x76, 0x31, 0x2f, 0x70, 0x6f, 0x73, 0x74, 0x43, 0x6f, 0x72, 0x70, 0x54, 0x69, 0x63, 0x6b,
	0x65, 0x74, 0x3a, 0x01, 0x2a, 0x42, 0x0f, 0x5a, 0x0d, 0x70, 0x6b, 0x67, 0x2f, 0x61, 0x6c, 0x65,
	0x78, 0x2f, 0x68, 0x6f, 0x6d, 0x65, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_home_corp_proto_rawDescOnce sync.Once
	file_home_corp_proto_rawDescData = file_home_corp_proto_rawDesc
)

func file_home_corp_proto_rawDescGZIP() []byte {
	file_home_corp_proto_rawDescOnce.Do(func() {
		file_home_corp_proto_rawDescData = protoimpl.X.CompressGZIP(file_home_corp_proto_rawDescData)
	})
	return file_home_corp_proto_rawDescData
}

var file_home_corp_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_home_corp_proto_goTypes = []interface{}{
	(*PostCorpTicketRequest)(nil),  // 0: xd.home.PostCorpTicketRequest
	(*PostCorpTicketResponse)(nil), // 1: xd.home.PostCorpTicketResponse
	(*GetCorpTicketRequest)(nil),   // 2: xd.home.GetCorpTicketRequest
	(*GetCorpTicketResponse)(nil),  // 3: xd.home.GetCorpTicketResponse
	(*emptypb.Empty)(nil),          // 4: google.protobuf.Empty
}
var file_home_corp_proto_depIdxs = []int32{
	4, // 0: xd.home.PostCorpTicketResponse.data:type_name -> google.protobuf.Empty
	2, // 1: xd.home.CropService.getCorpTicket:input_type -> xd.home.GetCorpTicketRequest
	0, // 2: xd.home.CropService.postCorpTicket:input_type -> xd.home.PostCorpTicketRequest
	3, // 3: xd.home.CropService.getCorpTicket:output_type -> xd.home.GetCorpTicketResponse
	1, // 4: xd.home.CropService.postCorpTicket:output_type -> xd.home.PostCorpTicketResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_home_corp_proto_init() }
func file_home_corp_proto_init() {
	if File_home_corp_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_home_corp_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostCorpTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_home_corp_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PostCorpTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_home_corp_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCorpTicketRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_home_corp_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*GetCorpTicketResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_home_corp_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_home_corp_proto_goTypes,
		DependencyIndexes: file_home_corp_proto_depIdxs,
		MessageInfos:      file_home_corp_proto_msgTypes,
	}.Build()
	File_home_corp_proto = out.File
	file_home_corp_proto_rawDesc = nil
	file_home_corp_proto_goTypes = nil
	file_home_corp_proto_depIdxs = nil
}
